### ISSUE TITLE
Proposal: switch thresholds to be memory used instead of memory free

### ISSUE THREAD

**Issue by sge-babrams** [sensu-plugins/sensu-plugins-memory-checks#5]
I think setting a threshold on memory left vs memory used does not seem as natural as most plugins are based on used threshold. 

If there is any chance of it passing I am more than happy to submit a PR. Either to adding additional doc as to how its used or changing it to be a usage threshold.

**Comment by mattyjones** [comment]
I am good with changing it to memory used.  @sge-babrams  Submit a PR and I would certainly take a look at it.

**Comment by maticmeznar** [comment]
I think both threshold types have valid use cases. Personally, I want to know when I'm running out of free memory (e.g., less than 64 MiB left), because that is actionable information and means a performance problem that applies to pretty much all computers, even those with only 1 GiB. "Memory used" threshold is only meaningful if you know how much memory that computer has, meaning you have to configure the threshold depending on total memory, increasing complexity.

**Comment by sge-babrams** [comment]
@maticmeznar I think that is a fair point.

I suppose a logical way to separate it would be when using --megabytes we could use MB remaining as opposed to percentages used. Alternatively we could have a flag to specify usage vs free. If either sounds good I will get together a PR.

@mattyjones what are your thoughts on this?

**Comment by mattyjones** [comment]
@maticmeznar  I like the idea of the flag.  I think it has the widest use case.

**Comment by tas50** [comment]
I'd also like to see this as a flag.  The current behavior is what a lot of people expect from the memory check and we should maintain that behavior for those users.

**Comment by sge-babrams** [comment]
@mattyjones @tas50 @maticmeznar PR ready for initial review its passing spec

**Comment by sge-babrams** [comment]
Also I switched out `free -m` to be os agnostic using vmstat gem

**Comment by mattyjones** [comment]
When I look at #6 I will also poke at this

**Comment by sge-babrams** [comment]
@mattyjones as https://github.com/sensu-plugins/sensu-plugins-memory-checks/pull/6 has landed this can be closed. can we tag and release new gem version please?
